# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca901f0e20553fcf3c2acf080d04b58607acdba4900160f44c5dc4e9c0056a3113114a20b8388661c057ebccaa33aecfabedb05baa243cbcefeff6d6a4217559

test:
  secret_key_base: 80adbacc30b93518a8cc6e30bd284762127f9579f15bc94bc0d2e64494d088585f220a13c9221ce739d0545d9447fc38fad4ba2cc15b63267602c3e47fefe9da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
